Fix zero Edisp, add replacement tally
idaholab/mytrim pull request #63
Opened 2017-05-11 20:46 UTC by dschwen

Also adds _Quick calculation of damage_ (Kinchin-Pease).

ACloses #62

2017-05-11 21:04 UTC, snschune requested changes

2017-05-11 21:04 UTC, snschune commented on apps/src/TrimRange.C
> +  _simconf->vacancies_created += _recoil->_E * 0.4 / _element->_Edisp;
we should actually do this
http://www.iue.tuwien.ac.at/phd/hoessinger/node47.html

2017-05-11 21:13 UTC, snschune commented on apps/src/TrimVacCount.C
> +  int x = _recoil->_pos(0);
What is `_recoil->_pos(0)`. Is that the x-coordinate?

2017-05-11 21:14 UTC, snschune commented on apps/src/TrimVacCount.C
> +  _vac_bin.resize(size);
this just adds zeros at the end if the other <>_bin is larger?

2017-05-11 21:15 UTC, snschune commented on trim.C
> +          replacementCollision();
replacement in this sense now includes replacement & substitution. I guess that is what we want.

2017-05-11 21:23 UTC, dschwen commented on apps/src/TrimRange.C
> +  _simconf->vacancies_created += _recoil->_E * 0.4 / _element->_Edisp;
Yes, _modified_ KP. I'll implement that.

2017-05-11 21:23 UTC, dschwen commented on apps/src/TrimVacCount.C
> +  int x = _recoil->_pos(0);
Yes

2017-05-11 21:23 UTC, dschwen commented on apps/src/TrimVacCount.C
> +  _vac_bin.resize(size);
Yes

2017-05-11 21:24 UTC, dschwen commented on trim.C
> +          replacementCollision();
Yes. The distinction can still be made in the callback if necessary.

2017-05-11 21:29 UTC, snschune commented on apps/src/TrimVacCount.C
> +  int x = _recoil->_pos(0);
Should't this be divided by some bin width to map it into a regular grid index?

2017-05-11 22:07 UTC, dschwen commented
Modified KP takes it from

```
Vacancies/ion: 2082.06 
```

to:

```
Vacancies/ion: 1536.79
```

for the 150keV Copper on Copper test. This is a lot closer to the SRIM quick damage result.

2017-05-11 23:40 UTC, snschune commented
👍

2017-05-11 23:41 UTC, snschune commented on apps/src/TrimVacCount.C
> +  int x = _recoil->_pos(0);
Still curious how this works exactly, but I'll merge it for now.

2017-05-11 23:41 UTC, merged

2017-05-12 00:06 UTC, dschwen commented on apps/src/TrimVacCount.C
> +  int x = _recoil->_pos(0);
The bin index is the depth in angstroms

2017-05-12 00:14 UTC, snschune commented on apps/src/TrimVacCount.C
> +  int x = _recoil->_pos(0);
Ok so you don't allow a different bin size but `delx = 1 A`